### ISSUE TITLE
Website certificate is expired

### ISSUE THREAD

**Issue by viktor02** [teacat/chaturbate-dvr#23]
```
Dec 23 18:07:38 local chaturbatedvr[1894]: 2022/12/23 18:07:38 [RECORDING] bethcoy is online! start fetching..
Dec 23 18:07:38 local chaturbatedvr[1894]: 2022/12/23 18:07:38 Get "https://edge15-alb.stream.highwebmedia.com/live-hls/amlst:bethcoy-sd-698f652c0d150a949546ee98de431142b12a44631ec21bfdc834627947415324_trns_h264/playlist.m3u8": x509: certificate has expired or is not yet valid: current time 2022-12-23T18:07:_h264/playlist.m3u8": x509: certificate has expired or is not yet valid: current time 2022-12-23T18:07:38+02:00 is after 2022-10-15T23:59:59Z
Dec 23 18:07:38 local chaturbatedvr[1894]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 23 18:07:38 local chaturbatedvr[1894]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x782c9c]
Dec 23 18:07:38 local chaturbatedvr[1894]: goroutine 1 [running]:
Dec 23 18:07:38 local chaturbatedvr[1894]: main.parseHLSSource(0xc0000ee8c0, 0x9d, 0xc0000ee8c0, 0x90, 0xc0000ee8c0, 0x90)
Dec 23 18:07:38 local chaturbatedvr[1894]:         /root/chaturbate-dvr/main.go:119 +0x9c
Dec 23 18:07:38 local chaturbatedvr[1894]: main.capture(0x7fff9c070f27, 0x7)
Dec 23 18:07:38 local chaturbatedvr[1894]:         /root/chaturbate-dvr/main.go:182 +0x13e
Dec 23 18:07:38 local chaturbatedvr[1894]: main.endpoint(0xc00004e800, 0xc00000e900, 0x6)
Dec 23 18:07:38 local chaturbatedvr[1894]:         /root/chaturbate-dvr/main.go:352 +0x7c5
Dec 23 18:07:38 local chaturbatedvr[1894]: github.com/urfave/cli/v2.(*App).RunContext(0xc00006ed00, 0x8b7d20, 0xc000016018, 0xc000012180, 0x3, 0x3, 0x0, 0x0)
Dec 23 18:07:38 local chaturbatedvr[1894]:         /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x70d
Dec 23 18:07:38 local chaturbatedvr[1894]: github.com/urfave/cli/v2.(*App).Run(...)
Dec 23 18:07:38 local chaturbatedvr[1894]:         /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
Dec 23 18:07:38 local chaturbatedvr[1894]: main.main()
Dec 23 18:07:38 local chaturbatedvr[1894]:         /root/chaturbate-dvr/main.go:390 +0x370
Dec 23 18:07:38 local systemd[1]: chaturbate.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 23 18:07:38 local systemd[1]: chaturbate.service: Failed with result 'exit-code'.
Dec 23 18:07:38 local systemd[1]: chaturbate.service: Consumed 3min 6.531s CPU time.
```
Can you add support for ignore expired certificates?

**Comment by YamiOdymel** [comment]
The Chaturbate server is using an expired certificate (~~wtf?~~),

it can't be fixed by simply ignore it, because your system will still stop it (a secure issue).

(1) Does it happen often? 

(2) Which `chaturbate-dvr` you downloaded from? From [`master` branch](https://github.com/teacat/chaturbate-dvr/tree/master/bin) OR [Alpha 0.8 Release](https://github.com/teacat/chaturbate-dvr/releases/tag/v0.8-alpha)?

I remember the [Alpha 0.8 Release](https://github.com/teacat/chaturbate-dvr/releases/tag/v0.8-alpha) program won't stop if an error was encountered, maybe try it 🤔?

**Comment by YamiOdymel** [comment]
Please download the [`Alpha 0.9`](https://github.com/teacat/chaturbate-dvr/releases/tag/v0.9-alpha) and use the `/bin/linux/chaturbate-dvr` (if you are using Linux)

It ignores the certificate check. Not sure if it includes the "expired certificate" but worth a try.

**Comment by viktor02** [comment]
I compiled from master branch yesterday. Thanks for "fixing" their errors, I'm going to try it :)
