### ISSUE TITLE
Another runtime error

### ISSUE THREAD

**Issue by renzzla** [teacat/chaturbate-dvr#27]
Hi, I had another instance of a long running process crashing using v0.92:

`2023/03/13 02:45:12 [37m[INFO] Tatekristin is not online, check again in 1 minute(s)[0m
2023/03/13 02:46:12 [37m[INFO] Tatekristin is not online, check again in 1 minute(s)[0m
2023/03/13 02:47:13 [32m[RECORDING] Tatekristin is online! start fetching..[0m
2023/03/13 02:47:14 [31mGet "": unsupported protocol scheme ""[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7275fd]

goroutine 1 [running]:
main.parseHLSSource({0x0, 0x0}, {0x0, 0x0})
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:123 +0x31d
main.capture({0x7fffe28ce78a, 0xb})
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:186 +0xd7
main.endpoint(0xc0001ae240?)
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:359 +0x5cb
github.com/urfave/cli/v2.(*App).RunContext(0xc000186d00, {0x864e30?, 0xc0001c4040}, {0xc000194150, 0x3, 0x3})
	/mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
	/mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:397 +0x3eb
`

**Comment by YamiOdymel** [comment]
Fixed in v0.93, please check https://github.com/teacat/chaturbate-dvr/releases/tag/v0.93-alpha

Program panicked because Chaturbate returned an invalid URL, related to #25, fixed the issue by adding more checks for empty response 😭👌
