### ISSUE TITLE
panic: interface conversion: m3u8.Playlist is nil, not *m3u8.MasterPlaylist

### ISSUE THREAD

**Issue by nephaste** [teacat/chaturbate-dvr#3]
since some days recording dot start

panic: interface conversion: m3u8.Playlist is nil, not *m3u8.MasterPlaylist

goroutine 1 [running]:
main.parseHLSSource(0xc0000def00, 0x9c, 0xc0000def00, 0x8f, 0xc0000def00, 0x8f)
        /build/chaturbate-dvr/main.go:97 +0x23f
main.capture(0x7ffc49fdf90e, 0x9)
        /build/chaturbate-dvr/main.go:132 +0xd3
main.endpoint(0xc00005c6c0, 0x0, 0x4)
        /build/chaturbate-dvr/main.go:271 +0x6c8
github.com/urfave/cli/v2.(*App).RunContext(0xc0000771e0, 0x869e70, 0xc0000180c8,                                                                     0xc000012180, 0x3, 0x3, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /build/chaturbate-dvr/main.go:304 +0x2b1

have any clue ?

**Comment by YamiOdymel** [comment]
Hmmmm, weird. The error was occurred because it cannot retrieve the `playlist.m3u8`, but the error also occurred when I watch Chaturbate with Chrome. 

It seems like it might be Chaturbate server issue with HTTP2 Protocol thing, not an issue of `teacat/chaturbate-dvr`. Does it work if you watch Chaturbate with Chrome? Or the video is also not loading and fallback to JPEG player (low FPS)?

![image](https://user-images.githubusercontent.com/7308718/148660507-6f6412db-f1df-40e6-a290-eb5ba5bfd215.png)

**Comment by nephaste** [comment]
yes all is working as expecting into a browser... it was not happening with all models... but some of them only
very strange
