### ISSUE TITLE
Enhancement: Paused option to saved channels and sort and tags in webui

### ISSUE THREAD

**Issue by robinhugy** [teacat/chaturbate-dvr#80]
Hey!
Can you add a new paused per channel option to chaturbate_channels.json?
"Paused": 0/1
And can you add sorting and maybe tags in webui?

Thanks for your work :]

**Comment by robinhugy** [comment]
Sorry, i forgot to explain.
When i start the program, all of the added cams start downloading/checking online status. I pause some unnecessary cams, but after i restart the program, all added cams start downloading again, because paused status not saved.

**Comment by robinhugy** [comment]
panic: send on closed channel

goroutine 78 [running]:
github.com/teacat/chaturbate-dvr/chaturbate.(*Manager).CreateChannel.func1()
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/manager.go:121 +0xe5
created by github.com/teacat/chaturbate-dvr/chaturbate.(*Manager).CreateChannel in goroutine 1
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/manager.go:117 +0x2d5

**Comment by robinhugy** [comment]
panic: send on closed channel

goroutine 55 [running]:
github.com/teacat/chaturbate-dvr/chaturbate.(*Manager).CreateChannel.func1()
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/manager.go:121 +0xe5
created by github.com/teacat/chaturbate-dvr/chaturbate.(*Manager).CreateChannel in goroutine 1
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/manager.go:117 +0x2d5

now i dont do anything

**Comment by YamiOdymel** [comment]
Should be fixed, no longer be an issue
