### ISSUE TITLE
Crash with error message

### ISSUE THREAD

**Issue by robinhugy** [teacat/chaturbate-dvr#81]
Hey!
I get an error message when the program crashing, i need to restart it manually. Crashing everyday, min. 1-2 times when use.

```
goroutine 50 [running]:
github.com/teacat/chaturbate-dvr/chaturbate.(*Manager).CreateChannel.func1()
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/manager.go:121 +0xe5
created by github.com/teacat/chaturbate-dvr/chaturbate.(*Manager).CreateChannel in goroutine 1
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/manager.go:117 +0x2d5
```

Need any more info about usage?

**Comment by YamiOdymel** [comment]
Is it randomly crashing? There should be an error message explaining why it crashed (few lines before the lines you pasted). Can you paste it?

Try copying chaturbate-dvr.exe to a new/empty folder and opening it. It might be caused by an odd channel making it crash.

**Comment by robinhugy** [comment]
I dont see anything else in cmd window.
Randomly, i dont do anything when crash. I have been using it for a week and added 18 channels.

Channel example:
```
{
        "Username": "VALIDCHANNELNAME",
        "FilenamePattern": "d:/videos/chaturbate/{{.Username}}/{{.Username}}_{{.Year}}_{{.Month}}_{{.Day}}-{{.Hour}}_{{.Minute}}_{{.Second}}",
        "Framerate": 30,
        "Resolution": 2160,
        "ResolutionFallback": "down",
        "SplitDuration": 0,
        "SplitFilesize": 0,
        "Interval": 1
    }
```

**Comment by YamiOdymel** [comment]
The program has been refactored, and this problem may no longer exist. Assuming it's fixed in [v2.0.0](https://github.com/teacat/chaturbate-dvr/releases/tag/v2.0.0).
